### PR TITLE
Integration of new Libraries

### PR DESCRIPTION
**Pull request by hypery2k**
Still WIP

* any fixes should be against the feature-branches 
* Link any errors here

### CODE REVIEW

**Comment by hypery2k** [comment]
the add via demo seems to be broken, maybe something with CD

**Comment by tmalatinszki** [comment]
Hi,

Will be there any support for item/group set operations like in the "old" version (removeItems, getById etc.)? As I see these are disappeared after switching to the new vis.js library.

Thanks,
Tamás

**Comment by hypery2k** [comment]
@tmalatinszki not sure right now, currently focus on getting the build changed to ng-packagr, see #348

I'll try to be compatible, but actually cannot promise it

related issue: see #351

**Comment by hypery2k** [comment]
I published version 3.0.0 which introduced breaking changes.

@tmalatinszki If you want to old functionality back, feel free to fill [an issue](https://github.com/visjs/ngx-vis/issues/new?template=feature_request.md) for that.

**Pull request merged**
